### ISSUE TITLE
Modularizing component leaves it without material-like style

### ISSUE THREAD

**Issue by cbeldacap** [demirk4n/material2-demo#1]
Hello @demirk4n , first of all thnx for updating the repo.

When I try to separate the "header" peace of code from `app` component and declaring as a different component and importing it with `<header></header>` (f.ex.), some features of material stop being like that, like the menu in the left-side.

(i leave you here a capture of the visual result)
![capture](https://cloud.githubusercontent.com/assets/20857839/21806789/aea1ab0e-d73b-11e6-983c-261803d89b15.PNG)

**Comment by cbeldacap** [comment]
Sorry, didn't know you were using styles from `app.component.css`

everything works fine

**Comment by demirk4n** [comment]
Hi @cbeldacap thank you for your feedback. I am glad to hear the issue is solved.
